app:
  name: go-web
  mode: release
  server:
    port: 9024
  database:
    - name: postgres
      type: postgres
      host: 172.17.112.1
      port: 5432
      dbname: postgres
      username: postgres
      password: "123456"
  log:
    full:
      path: E:\\
    err:
      path: E:\\
consul:
  address: localhost:8500
  schema: http
  token: 8f802f1f-4ce7-40b1-8fe5-83470cf75ba4