app:
  name: go-web
  mode: release
  server:
    port: 9024
  database:
    - name: postgres
      type: postgres
      host: localhost
      port: 5432
      dbname: postgres
      username: postgres
      password: "123456"
  log:
    full:
      path: E:\\
    err:
      path: E:\\
